"on":
    push:
        branches:
            - patch-1
name: Deploy to toolkit-backend
jobs:
    porter-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set Github tag
              id: vars
              run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
            - name: Setup porter
              uses: porter-dev/setup-porter@v0.1.0
            - name: Deploy stack
              timeout-minutes: 30
              run: exec porter apply -f ./porter.yaml
              env:
                PORTER_APP_NAME: toolkit-backend
                PORTER_CLUSTER: "4706"
                PORTER_DEPLOYMENT_TARGET_ID: cd749bcc-8bdb-48fa-8841-afbd4ab75d52
                PORTER_HOST: https://dashboard.porter.run
                PORTER_PR_NUMBER: ${{ github.event.number }}
                PORTER_PROJECT: "15204"
                PORTER_REPO_NAME: ${{ github.event.repository.name }}
                PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
                PORTER_TOKEN: ${{ secrets.PORTER_APP_15204_4706 }}
